### ISSUE TITLE
Error redis connection when executing the image

### ISSUE THREAD

**Issue by masbenx** [adempiere/proxy-adempiere-api-docker#17]
when I run the docker using command

docker run -it -d \
        --name Proxy-ADempiere-API \
        -p 8085:8085 \
        -e AD_DEFAULT_HOST="localhost" \
        -e AD_DEFAULT_PORT="50059" \
        -e VS_ENV="dev" \
        erpya/proxy-adempiere-api
        
  the result show error :

`error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 date=Wed Feb 24 2021 11:39:15 GMT+0000 (Coordinated Universal Time), pid=83, uid=0, gid=0, cwd=/var/www/proxy-adempiere-api, execPath=/usr/local/bin/node, version=v10.23.3, argv=[/var/www/proxy-adempiere-api/node_modules/.bin/ts-node, /var/www/proxy-adempiere-api/src], rss=324349952, heapTotal=246333440, heapUsed=203420224, external=110594, loadavg=[0.37109375, 0.2294921875, 0.193359375], uptime=29507, trace=[column=14, file=net.js, function=TCPConnectWrap.afterConnect [as oncomplete], line=1107, method=afterConnect [as oncomplete], native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379,     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)]`

**Comment by rhmnrf** [comment]
Upvote!

**Comment by EdwinBetanc0urt** [comment]
Hi @masbenx @rahmanarifm A quick solution is to run ```docker-compose -f docker-compose.yml up``` in the https://github.com/adempiere/proxy-adempiere-api repository to create the redis container.
